---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: all
  become: true
  gather_facts: no
  roles:
  - base

- hosts: workstations
  become: true
  gather_facts: no
  roles:
  - workstations

- hosts: web_servers
  become: true
  gather_facts: no
  roles:
  - web_servers

- hosts: db_servers
  become: true
  gather_facts: no
  roles:
  - db_servers

- hosts: file_servers
  become: true
  gather_facts: no
  roles:
  - file_servers
