- name: install apache2 package
  tags: apache,apache2,debian
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: Start Apache
  tags: apache,http
  service:
    name: apache2
    state: started
    enabled: yes

- name: change E-Mail for admin profile
  tags: apache
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerAdmin'
    line: Serveradmin maik.kaeseberg@shd-online.de
  register: apache2

- name: restart Apache
  tags: apache,http
  service:
    name: apache2
    state: restarted
  when: apache2.changed

- name: copy html-file
  tags: apache, apache2, http
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
