- name: install apache2 package
  tags: apache,apache2,debian
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Debian"

- name: Start Apache
  tags: apache,http
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change E-Mail for admin profile
  tags: apache
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerAdmin'
    line: Serveradmin someone@shd-online.de
  notify: restart_apache

- name: copy html-file
  tags: apache, apache2, http
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
